# Generated by Django 2.0.2 on 2018-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0002_auto_20180306_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=255)),
            ],
        ),
    ]
