# Generated by Django 2.0.2 on 2018-03-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0003_classcreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassCreation',
        ),
    ]
