# Generated by Django 2.0.2 on 2018-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0004_delete_classcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='abbr',
            field=models.CharField(max_length=4, verbose_name='abbreviation'),
        ),
    ]
