# Generated by Django 2.0.2 on 2018-04-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0006_selection_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
