# Generated by Django 2.0.2 on 2018-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0008_auto_20180402_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='owner',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hours',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slots_available',
            field=models.IntegerField(default=3),
        ),
    ]
