# Generated by Django 2.0.2 on 2018-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0009_auto_20180402_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='owner',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='slots',
            field=models.IntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
