# Generated by Django 2.0 on 2018-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0010_auto_20180402_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='slots',
        ),
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.IntegerField(default=3),
        ),
    ]
