# Generated by Django 2.0 on 2018-04-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0011_auto_20180402_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slots',
        ),
    ]
