# Generated by Django 2.0 on 2018-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0012_remove_event_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.IntegerField(default=3),
        ),
    ]
