# Generated by Django 2.0 on 2018-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0013_event_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slots',
            field=models.IntegerField(),
        ),
    ]
