# Generated by Django 2.0 on 2018-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0014_auto_20180402_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slots',
            field=models.CharField(max_length=2),
        ),
    ]
