# Generated by Django 2.0 on 2018-04-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0015_auto_20180402_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slots',
        ),
    ]
