# Generated by Django 2.0.2 on 2018-04-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0016_remove_event_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.IntegerField(default=3),
        ),
    ]
