# Generated by Django 2.0.2 on 2018-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0017_event_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slot1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='slot2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='slot3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
