# Generated by Django 2.0.2 on 2018-04-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0018_auto_20180405_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slot1',
            field=models.CharField(default='Slot 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot2',
            field=models.CharField(default='Slot 2', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot3',
            field=models.CharField(default='Slot 3', max_length=20),
        ),
    ]
