# Generated by Django 2.0.2 on 2018-04-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0019_auto_20180405_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slot1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot3',
            field=models.CharField(default='', max_length=20),
        ),
    ]
