# Generated by Django 2.0.2 on 2018-03-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_classcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='children1',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='children2',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
