# Generated by Django 2.0.2 on 2018-03-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180313_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='children1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='children2',
            field=models.CharField(max_length=255),
        ),
    ]
