# Generated by Django 2.0.2 on 2018-03-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180313_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='children1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='children2',
        ),
    ]
