# Generated by Django 2.0.2 on 2018-03-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180313_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children1', models.CharField(max_length=255)),
                ('children2', models.CharField(max_length=255)),
            ],
        ),
    ]
