# Generated by Django 2.0.2 on 2018-03-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_parentcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcreation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='parentcreation',
            name='password2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='parentcreation',
            name='username',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
