# Generated by Django 2.0.2 on 2018-03-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180313_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcreation',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parentcreation',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parentcreation',
            name='password1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='children1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='children2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
