# Generated by Django 2.0 on 2018-03-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20180313_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcreation',
            name='password1',
        ),
    ]
