# Generated by Django 2.0.2 on 2018-03-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_parentcreation_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassCreation',
        ),
    ]
