# Generated by Django 2.0 on 2018-03-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20180317_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcreation',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
