# Generated by Django 2.0 on 2018-03-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20180318_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcreation',
            name='children1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='children2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='password2',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='parentcreation',
            name='username',
            field=models.CharField(max_length=254),
        ),
    ]
