# Generated by Django 2.0.2 on 2018-03-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20180328_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentcreation',
            old_name='current_hours',
            new_name='curent_hours',
        ),
    ]
