# Generated by Django 2.0 on 2018-03-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20180328_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcreation',
            name='total_hours',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
