# Generated by Django 2.0 on 2018-03-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20180328_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcreation',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
