# Generated by Django 2.0.2 on 2018-03-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20180328_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentCreation',
        ),
    ]
