# Generated by Django 2.0.2 on 2018-03-31 06:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_delete_parentcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('password2', models.CharField(max_length=254)),
                ('children1', models.CharField(max_length=255)),
                ('children2', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('curent_hours', models.IntegerField(default=0)),
                ('monthly_hours', models.IntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
