# Generated by Django 2.0.2 on 2018-03-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20180331_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcreation',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='parentcreation',
            name='password',
        ),
    ]
